# Generated by Django 4.2.7 on 2024-03-19 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, verbose_name='Estado de venta')),
            ],
            options={
                'verbose_name': 'Estado de venta',
                'verbose_name_plural': 'Estados de venta',
                'db_table': 'estado_Venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Tipo de pago')),
            ],
            options={
                'verbose_name': 'Tipo de pago',
                'verbose_name_plural': 'Tipos de pago',
                'db_table': 'tipo_Pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha de venta')),
                ('price', models.FloatField(verbose_name='Precio de venta')),
                ('amount', models.FloatField(verbose_name='Abono inicial')),
                ('totalVAT', models.FloatField(verbose_name='Total IVA venta')),
                ('totalPrice', models.FloatField(verbose_name='Precio total de venta')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.request', verbose_name='Solicitud')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.state_sale', verbose_name='estado de la venta')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.type_payment', verbose_name='Tipo de pago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago')),
                ('paymentdate', models.DateField(default=datetime.date.today, verbose_name='Fecha de abono')),
                ('paymentI', models.FloatField(verbose_name='Cantidad de abono')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.sale', verbose_name='venta')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.type_payment', verbose_name='Tipo de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
                'ordering': ['id'],
            },
        ),
    ]
