# Generated by Django 4.2.7 on 2023-12-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_service',
            name='state',
            field=models.CharField(max_length=1000, verbose_name='Estado de servicio'),
        ),
    ]
