# Generated by Django 4.2.7 on 2023-12-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha actividad')),
                ('novelty', models.CharField(max_length=50, verbose_name='Novedad de actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'Actividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Novelty_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelty', models.CharField(max_length=30, verbose_name='Novedad de producción')),
            ],
            options={
                'verbose_name': 'Novedad de producción',
                'verbose_name_plural': 'Novedades de producción',
                'db_table': 'Novedad_Produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='State_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, verbose_name='Estado de actividad')),
            ],
            options={
                'verbose_name': 'Estado de actividad',
                'verbose_name_plural': 'Estados de actividad',
                'db_table': 'Estado_Actividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='State_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, verbose_name='Estado de producción')),
            ],
            options={
                'verbose_name': 'Estado de producción',
                'verbose_name_plural': 'Estados de producción',
                'db_table': 'Estado_Produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Tipo de actividad')),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividad',
                'db_table': 'Tipo_Actividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Tipo de producción')),
            ],
            options={
                'verbose_name': 'Tipo de producción',
                'verbose_name_plural': 'Tipos de producción',
                'db_table': 'Tipo_Produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha produccion')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.activity', verbose_name='actividad')),
                ('novelty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.novelty_production', verbose_name='novedad de produccion')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.state_production', verbose_name='estado de produccion')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.type_production', verbose_name='Tipo de produccion')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Producciones',
                'db_table': 'Produccion',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.state_activity', verbose_name='estado de la actividad'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.type_activity', verbose_name='Tipo de actividad'),
        ),
    ]
